"""Naming convention and path resolution for the ONNX model files.

Naming convention:
    diffusion_size{S}_timesteps{T}_step{P}.onnx          : ReLU model (no activation tag, for backward compatibility)
    diffusion_{act}_size{S}_timesteps{T}_step{P}.onnx    : SiLU / GELU model
    sim_ prefix                                          : simplified with onnxsim
    pwl{K}_ prefix                                       : activations replaced by a piecewise-linear approximation (K knots)

Note: the independent models of the interval-counting experiment (one p-value = one model)
are trained inside each job and then discarded (train_synthetic_model_ephemeral in model.py).
They are never written to disk, so this naming convention does not apply to them.
"""

SUPPORTED_ACT_FNS = {"relu", "silu", "gelu"}


def model_config(category: str) -> tuple[str, int, int]:
    """Return the model directory and (timesteps, sampling_step) for a category.

    All synthetic categories (iid / corr / skewnorm / ... / syn) share the same models.
    """
    return "../model/syn", 460, 115


def build_model_filename(
    image_size: int,
    timesteps: int,
    step: int,
    act_fn: str = "relu",
    pwl_knots: int = 0,
    simplified: bool = True,
) -> str:
    """Build a model file name.

    Parameters
    ----------
    pwl_knots : int
        0 for the model with its original activation; a positive value for the
        model whose activations are replaced by the PWL approximation.
    simplified : bool
        When pwl_knots == 0, choose between the onnxsim-simplified model (sim_)
        and the raw exported model.
    """
    if act_fn not in SUPPORTED_ACT_FNS:
        raise ValueError(f"Unsupported activation function: {act_fn}")
    # ReLU model files carry no activation name (backward compatibility)
    act_tag = "" if act_fn == "relu" else f"{act_fn}_"
    if pwl_knots > 0:
        prefix = f"pwl{pwl_knots}_"
    elif simplified:
        prefix = "sim_"
    else:
        prefix = ""
    return f"{prefix}diffusion_{act_tag}size{image_size}_timesteps{timesteps}_step{step}.onnx"


def resolve_onnx_path(
    category: str,
    image_size: int,
    act_fn: str = "relu",
    pwl_knots: int = 0,
    for_inference: bool = True,
) -> str:
    """Resolve the path of the ONNX model for a category and settings.

    Parameters
    ----------
    for_inference : bool
        If True, raise an error for settings that cannot be used for selective
        inference (e.g., a smooth activation without the PWL approximation).
        Set to False for forward-only uses such as comparing the outputs
        before and after the approximation.
    """
    if for_inference:
        validate_activation_config(act_fn, pwl_knots)
    model_dir, timesteps, step = model_config(category)
    filename = build_model_filename(image_size, timesteps, step, act_fn, pwl_knots)
    return f"{model_dir}/{filename}"


def validate_activation_config(act_fn: str, pwl_knots: int):
    """Check that (act_fn, pwl_knots) is a valid combination for selective inference."""
    if act_fn == "relu" and pwl_knots != 0:
        raise ValueError("ReLU is already piecewise linear; pwl_knots must be 0.")
    if act_fn in ("silu", "gelu") and pwl_knots <= 0:
        raise ValueError(
            f"{act_fn} model requires a piecewise-linear approximation for valid "
            "selective inference. Specify pwl_knots > 0 and use the model "
            "generated by rewrite_pwl.py."
        )


def model_result_tag(act_fn: str = "relu", pwl_knots: int = 0) -> str:
    """Tag used to separate result directories (empty for the default ReLU setting)."""
    if act_fn == "relu" and pwl_knots == 0:
        return ""
    return f"pwl/{act_fn}{pwl_knots}"
